//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/Inputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Inputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Inputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Inputs"",
    ""maps"": [
        {
            ""name"": ""GingerKale"",
            ""id"": ""9618bf74-a072-4b2c-8bfa-6ca6596d0356"",
            ""actions"": [
                {
                    ""name"": ""fillGingerKale"",
                    ""type"": ""Button"",
                    ""id"": ""e2d994ab-157b-42ce-903e-ea307057ea78"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""66a499a8-7cf9-47bd-a228-e441079018f2"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fillGingerKale"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b30f14b6-9da2-44a6-8396-ec78d6cdc165"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fillGingerKale"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c024930b-4099-4607-80ff-294840dd1bcd"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""fillGingerKale"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GingerKale
        m_GingerKale = asset.FindActionMap("GingerKale", throwIfNotFound: true);
        m_GingerKale_fillGingerKale = m_GingerKale.FindAction("fillGingerKale", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GingerKale
    private readonly InputActionMap m_GingerKale;
    private IGingerKaleActions m_GingerKaleActionsCallbackInterface;
    private readonly InputAction m_GingerKale_fillGingerKale;
    public struct GingerKaleActions
    {
        private @Inputs m_Wrapper;
        public GingerKaleActions(@Inputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @fillGingerKale => m_Wrapper.m_GingerKale_fillGingerKale;
        public InputActionMap Get() { return m_Wrapper.m_GingerKale; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GingerKaleActions set) { return set.Get(); }
        public void SetCallbacks(IGingerKaleActions instance)
        {
            if (m_Wrapper.m_GingerKaleActionsCallbackInterface != null)
            {
                @fillGingerKale.started -= m_Wrapper.m_GingerKaleActionsCallbackInterface.OnFillGingerKale;
                @fillGingerKale.performed -= m_Wrapper.m_GingerKaleActionsCallbackInterface.OnFillGingerKale;
                @fillGingerKale.canceled -= m_Wrapper.m_GingerKaleActionsCallbackInterface.OnFillGingerKale;
            }
            m_Wrapper.m_GingerKaleActionsCallbackInterface = instance;
            if (instance != null)
            {
                @fillGingerKale.started += instance.OnFillGingerKale;
                @fillGingerKale.performed += instance.OnFillGingerKale;
                @fillGingerKale.canceled += instance.OnFillGingerKale;
            }
        }
    }
    public GingerKaleActions @GingerKale => new GingerKaleActions(this);
    public interface IGingerKaleActions
    {
        void OnFillGingerKale(InputAction.CallbackContext context);
    }
}
